# Generated by Django 2.0 on 2018-06-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lead_text',
            field=models.TextField(default='To be added'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
